//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_
{
    using System;
    using System.Collections.Generic;
    
    public partial class countryes
    {
        public countryes()
        {
            this.languages = new HashSet<languages>();
        }
    
        public int Id { get; set; }
        public string country { get; set; }
    
        public virtual ICollection<languages> languages { get; set; }
    }
}
