//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_
{
    using System;
    using System.Collections.Generic;
    
    public partial class languages
    {
        public languages()
        {
            this.books = new HashSet<books>();
        }
    
        public int Id { get; set; }
        public string languageName { get; set; }
        public int countryesId { get; set; }
    
        public virtual ICollection<books> books { get; set; }
        public virtual countryes countryes { get; set; }
    }
}
